import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Navbar } from "@/components/layout/Navbar";
import { GlobalMapLayer } from "@/components/map/GlobalMapLayer";

// ... existing imports

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-slate-200 bg-slate-950`}
      >
        <Navbar />
        <GlobalMapLayer />
        <div className="relative z-10 w-full h-full min-h-screen pointer-events-none">
          {/* Pages verify their own pointer-events-auto where needed */}
          {children}
        </div>
      </body>
    </html>
  );
}
